# Preprocess MLS

In [20]:
from IPython.display import display
import pandas as pd

# Define file path
file_path = '../data/5_MLS_raw/hon-t07.xls'

# Try reading the Excel file using xlrd engine
df = pd.read_excel(file_path, engine='xlrd', header=1, skiprows=7)
df = df[:73]

# Change column names
df = df.rename(columns={'Unnamed: 0': 'year'})

# Extract only monthly data
df = df[['year', 'Jan.', 'Feb.', 'Mar.', 'Apr.', 'May', 'Jun.', 'Jul.', 'Aug.', 'Sep.', 'Oct.', 'Nov.', 'Dec.']]

# Convert wide format to long format
df = df.melt(id_vars=['year'], var_name='month', value_name='wage_indices')

# Replace values in months
month_dict = {
    'Jan.': '01', 'Feb.': '02', 'Mar.': '03', 'Apr.': '04', 
    'May': '05', 'Jun.': '06', 'Jul.': '07', 'Aug.': '08', 
    'Sep.': '09', 'Oct.': '10', 'Nov.': '11', 'Dec.': '12'
}
df['month'] = df['month'].replace(month_dict)

# Sort dataframe
df = df.sort_values(by=['year', 'month'])

# Omit invalid data
df = df[df['wage_indices']!='-']
df = df.reset_index(drop=True)

# show dataframe
display(df)

     year month wage_indices
0    1990    01         81.7
1    1990    02         75.3
2    1990    03         82.4
3    1990    04         78.4
4    1990    05         77.8
..    ...   ...          ...
415  2024    08           93
416  2024    09         91.6
417  2024    10         91.9
418  2024    11         96.9
419  2024    12        193.9

[420 rows x 3 columns]

In [ ]:
import os

# save MLS data
save_dir = '../data/6_MLS_structured'
os.makedirs(save_dir, exist_ok=True)

# Define file paths using relative paths
csv_file_path = os.path.join(save_dir, 'MLS.csv')
pickle_file_path = os.path.join(save_dir, 'MLS.pkl')

# Save DataFrame to CSV
df.to_csv(csv_file_path, index=False, encoding='utf-8-sig')
# Save DataFrame to Pickle
df.to_pickle(pickle_file_path)